# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/base/v1beta3/memory.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.v1beta3 import attribute_pb2 as akash_dot_base_dot_v1beta3_dot_attribute__pb2
from akash.proto.akash.base.v1beta3 import resourcevalue_pb2 as akash_dot_base_dot_v1beta3_dot_resourcevalue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61kash/base/v1beta3/memory.proto\x12\x12\x61kash.base.v1beta3\x1a\x14gogoproto/gogo.proto\x1a\"akash/base/v1beta3/attribute.proto\x1a&akash/base/v1beta3/resourcevalue.proto\"\xde\x01\n\x06Memory\x12P\n\x08quantity\x18\x01 \x01(\x0b\x32!.akash.base.v1beta3.ResourceValueB\x1b\xc8\xde\x1f\x00\xea\xde\x1f\x04size\xf2\xde\x1f\x0byaml:\"size\"\x12|\n\nattributes\x18\x02 \x03(\x0b\x32\x1d.akash.base.v1beta3.AttributeBI\xc8\xde\x1f\x00\xea\xde\x1f\x14\x61ttributes,omitempty\xf2\xde\x1f\x1byaml:\"attributes,omitempty\"\xaa\xdf\x1f\nAttributes:\x04\xe8\xa0\x1f\x01\x42:Z8github.com/akash-network/akash-api/go/node/types/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.base.v1beta3.memory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/akash-network/akash-api/go/node/types/v1beta3'
  _globals['_MEMORY'].fields_by_name['quantity']._options = None
  _globals['_MEMORY'].fields_by_name['quantity']._serialized_options = b'\310\336\037\000\352\336\037\004size\362\336\037\013yaml:\"size\"'
  _globals['_MEMORY'].fields_by_name['attributes']._options = None
  _globals['_MEMORY'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\024attributes,omitempty\362\336\037\033yaml:\"attributes,omitempty\"\252\337\037\nAttributes'
  _globals['_MEMORY']._options = None
  _globals['_MEMORY']._serialized_options = b'\350\240\037\001'
  _globals['_MEMORY']._serialized_start=154
  _globals['_MEMORY']._serialized_end=376
# @@protoc_insertion_point(module_scope)
