# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/cert/v1beta3/query.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from akash.proto.cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from akash.proto.akash.cert.v1beta3 import cert_pb2 as akash_dot_cert_dot_v1beta3_dot_cert__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61kash/cert/v1beta3/query.proto\x12\x12\x61kash.cert.v1beta3\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1d\x61kash/cert/v1beta3/cert.proto\"\xa3\x01\n\x13\x43\x65rtificateResponse\x12_\n\x0b\x63\x65rtificate\x18\x01 \x01(\x0b\x32\x1f.akash.cert.v1beta3.CertificateB)\xc8\xde\x1f\x00\xea\xde\x1f\x0b\x63\x65rtificate\xf2\xde\x1f\x12yaml:\"certificate\"\x12+\n\x06serial\x18\x02 \x01(\tB\x1b\xea\xde\x1f\x06serial\xf2\xde\x1f\ryaml:\"serial\"\"\x93\x01\n\x18QueryCertificatesRequest\x12;\n\x06\x66ilter\x18\x01 \x01(\x0b\x32%.akash.cert.v1beta3.CertificateFilterB\x04\xc8\xde\x1f\x00\x12:\n\npagination\x18\x02 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\xb5\x01\n\x19QueryCertificatesResponse\x12[\n\x0c\x63\x65rtificates\x18\x01 \x03(\x0b\x32\'.akash.cert.v1beta3.CertificateResponseB\x1c\xc8\xde\x1f\x00\xaa\xdf\x1f\x14\x43\x65rtificatesResponse\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse2\xa4\x01\n\x05Query\x12\x9a\x01\n\x0c\x43\x65rtificates\x12,.akash.cert.v1beta3.QueryCertificatesRequest\x1a-.akash.cert.v1beta3.QueryCertificatesResponse\"-\x82\xd3\xe4\x93\x02\'\x12%/akash/cert/v1beta3/certificates/listB9Z7github.com/akash-network/akash-api/go/node/cert/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.cert.v1beta3.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/akash-network/akash-api/go/node/cert/v1beta3'
  _globals['_CERTIFICATERESPONSE'].fields_by_name['certificate']._options = None
  _globals['_CERTIFICATERESPONSE'].fields_by_name['certificate']._serialized_options = b'\310\336\037\000\352\336\037\013certificate\362\336\037\022yaml:\"certificate\"'
  _globals['_CERTIFICATERESPONSE'].fields_by_name['serial']._options = None
  _globals['_CERTIFICATERESPONSE'].fields_by_name['serial']._serialized_options = b'\352\336\037\006serial\362\336\037\ryaml:\"serial\"'
  _globals['_QUERYCERTIFICATESREQUEST'].fields_by_name['filter']._options = None
  _globals['_QUERYCERTIFICATESREQUEST'].fields_by_name['filter']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYCERTIFICATESRESPONSE'].fields_by_name['certificates']._options = None
  _globals['_QUERYCERTIFICATESRESPONSE'].fields_by_name['certificates']._serialized_options = b'\310\336\037\000\252\337\037\024CertificatesResponse'
  _globals['_QUERY'].methods_by_name['Certificates']._options = None
  _globals['_QUERY'].methods_by_name['Certificates']._serialized_options = b'\202\323\344\223\002\'\022%/akash/cert/v1beta3/certificates/list'
  _globals['_CERTIFICATERESPONSE']._serialized_start=182
  _globals['_CERTIFICATERESPONSE']._serialized_end=345
  _globals['_QUERYCERTIFICATESREQUEST']._serialized_start=348
  _globals['_QUERYCERTIFICATESREQUEST']._serialized_end=495
  _globals['_QUERYCERTIFICATESRESPONSE']._serialized_start=498
  _globals['_QUERYCERTIFICATESRESPONSE']._serialized_end=679
  _globals['_QUERY']._serialized_start=682
  _globals['_QUERY']._serialized_end=846
# @@protoc_insertion_point(module_scope)
