# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/provider/v1/service.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from akash.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from akash.proto.akash.provider.v1 import status_pb2 as akash_dot_provider_dot_v1_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61kash/provider/v1/service.proto\x12\x11\x61kash.provider.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1e\x61kash/provider/v1/status.proto2\xa9\x01\n\x0bProviderRPC\x12U\n\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x19.akash.provider.v1.Status\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\n/v1/statusb\x01*\x12\x43\n\x0cStreamStatus\x12\x16.google.protobuf.Empty\x1a\x19.akash.provider.v1.Status0\x01\x42\x33Z1github.com/akash-network/akash-api/go/provider/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.provider.v1.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/akash-network/akash-api/go/provider/v1'
  _globals['_PROVIDERRPC'].methods_by_name['GetStatus']._options = None
  _globals['_PROVIDERRPC'].methods_by_name['GetStatus']._serialized_options = b'\202\323\344\223\002\017\022\n/v1/statusb\001*'
  _globals['_PROVIDERRPC']._serialized_start=146
  _globals['_PROVIDERRPC']._serialized_end=315
# @@protoc_insertion_point(module_scope)
