# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/manifest/v2beta1/serviceexpose.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.manifest.v2beta1 import httpoptions_pb2 as akash_dot_manifest_dot_v2beta1_dot_httpoptions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*akash/manifest/v2beta1/serviceexpose.proto\x12\x16\x61kash.manifest.v2beta1\x1a\x14gogoproto/gogo.proto\x1a(akash/manifest/v2beta1/httpoptions.proto\"\xc3\x04\n\rServiceExpose\x12%\n\x04port\x18\x01 \x01(\rB\x17\xea\xde\x1f\x04port\xf2\xde\x1f\x0byaml:\"port\"\x12>\n\rexternal_port\x18\x02 \x01(\rB\'\xea\xde\x1f\x0c\x65xternalPort\xf2\xde\x1f\x13yaml:\"externalPort\"\x12;\n\x05proto\x18\x03 \x01(\tB,\xea\xde\x1f\x05proto\xf2\xde\x1f\x0cyaml:\"proto\"\xfa\xde\x1f\x0fServiceProtocol\x12.\n\x07service\x18\x04 \x01(\tB\x1d\xea\xde\x1f\x07service\xf2\xde\x1f\x0eyaml:\"service\"\x12+\n\x06global\x18\x05 \x01(\x08\x42\x1b\xea\xde\x1f\x06global\xf2\xde\x1f\ryaml:\"global\"\x12(\n\x05hosts\x18\x06 \x03(\tB\x19\xea\xde\x1f\x05hosts\xf2\xde\x1f\x0cyaml:\"hosts\"\x12\x80\x01\n\x0chttp_options\x18\x07 \x01(\x0b\x32\x30.akash.manifest.v2beta1.ServiceExposeHTTPOptionsB8\xc8\xde\x1f\x00\xe2\xde\x1f\x0bHTTPOptions\xea\xde\x1f\x0bhttpOptions\xf2\xde\x1f\x12yaml:\"httpOptions\"\x12%\n\x02ip\x18\x08 \x01(\tB\x19\xe2\xde\x1f\x02IP\xea\xde\x1f\x02ip\xf2\xde\x1f\tyaml:\"ip\"\x12]\n\x18\x65ndpoint_sequence_number\x18\t \x01(\rB;\xea\xde\x1f\x16\x65ndpointSequenceNumber\xf2\xde\x1f\x1dyaml:\"endpointSequenceNumber\"B@Z6github.com/akash-network/akash-api/go/manifest/v2beta1\xd8\xe1\x1e\x00\x80\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.manifest.v2beta1.serviceexpose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/akash-network/akash-api/go/manifest/v2beta1\330\341\036\000\200\342\036\001'
  _globals['_SERVICEEXPOSE'].fields_by_name['port']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['port']._serialized_options = b'\352\336\037\004port\362\336\037\013yaml:\"port\"'
  _globals['_SERVICEEXPOSE'].fields_by_name['external_port']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['external_port']._serialized_options = b'\352\336\037\014externalPort\362\336\037\023yaml:\"externalPort\"'
  _globals['_SERVICEEXPOSE'].fields_by_name['proto']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['proto']._serialized_options = b'\352\336\037\005proto\362\336\037\014yaml:\"proto\"\372\336\037\017ServiceProtocol'
  _globals['_SERVICEEXPOSE'].fields_by_name['service']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['service']._serialized_options = b'\352\336\037\007service\362\336\037\016yaml:\"service\"'
  _globals['_SERVICEEXPOSE'].fields_by_name['global']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['global']._serialized_options = b'\352\336\037\006global\362\336\037\ryaml:\"global\"'
  _globals['_SERVICEEXPOSE'].fields_by_name['hosts']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['hosts']._serialized_options = b'\352\336\037\005hosts\362\336\037\014yaml:\"hosts\"'
  _globals['_SERVICEEXPOSE'].fields_by_name['http_options']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['http_options']._serialized_options = b'\310\336\037\000\342\336\037\013HTTPOptions\352\336\037\013httpOptions\362\336\037\022yaml:\"httpOptions\"'
  _globals['_SERVICEEXPOSE'].fields_by_name['ip']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['ip']._serialized_options = b'\342\336\037\002IP\352\336\037\002ip\362\336\037\tyaml:\"ip\"'
  _globals['_SERVICEEXPOSE'].fields_by_name['endpoint_sequence_number']._options = None
  _globals['_SERVICEEXPOSE'].fields_by_name['endpoint_sequence_number']._serialized_options = b'\352\336\037\026endpointSequenceNumber\362\336\037\035yaml:\"endpointSequenceNumber\"'
  _globals['_SERVICEEXPOSE']._serialized_start=135
  _globals['_SERVICEEXPOSE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
