# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/cluster.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.inventory.v1 import node_pb2 as akash_dot_inventory_dot_v1_dot_node__pb2
from akash.proto.akash.inventory.v1 import storage_pb2 as akash_dot_inventory_dot_v1_dot_storage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n akash/inventory/v1/cluster.proto\x12\x12\x61kash.inventory.v1\x1a\x14gogoproto/gogo.proto\x1a\x1d\x61kash/inventory/v1/node.proto\x1a akash/inventory/v1/storage.proto\"\xd7\x01\n\x07\x43luster\x12X\n\x05nodes\x18\x01 \x03(\x0b\x32\x18.akash.inventory.v1.NodeB/\xc8\xde\x1f\x00\xe2\xde\x1f\x05Nodes\xea\xde\x1f\x05nodes\xf2\xde\x1f\x0cyaml:\"nodes\"\xaa\xdf\x1f\x05Nodes\x12l\n\x07storage\x18\x02 \x03(\x0b\x32\x1b.akash.inventory.v1.StorageB>\xc8\xde\x1f\x00\xe2\xde\x1f\x07Storage\xea\xde\x1f\x07storage\xf2\xde\x1f\x0eyaml:\"storage\"\xaa\xdf\x1f\x0e\x43lusterStorage:\x04\xe8\xa0\x1f\x00\x42\x34Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.cluster_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_CLUSTER'].fields_by_name['nodes']._options = None
  _globals['_CLUSTER'].fields_by_name['nodes']._serialized_options = b'\310\336\037\000\342\336\037\005Nodes\352\336\037\005nodes\362\336\037\014yaml:\"nodes\"\252\337\037\005Nodes'
  _globals['_CLUSTER'].fields_by_name['storage']._options = None
  _globals['_CLUSTER'].fields_by_name['storage']._serialized_options = b'\310\336\037\000\342\336\037\007Storage\352\336\037\007storage\362\336\037\016yaml:\"storage\"\252\337\037\016ClusterStorage'
  _globals['_CLUSTER']._options = None
  _globals['_CLUSTER']._serialized_options = b'\350\240\037\000'
  _globals['_CLUSTER']._serialized_start=144
  _globals['_CLUSTER']._serialized_end=359
# @@protoc_insertion_point(module_scope)
