# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/cpu.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.inventory.v1 import resourcepair_pb2 as akash_dot_inventory_dot_v1_dot_resourcepair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61kash/inventory/v1/cpu.proto\x12\x12\x61kash.inventory.v1\x1a\x14gogoproto/gogo.proto\x1a%akash/inventory/v1/resourcepair.proto\"\xd1\x01\n\x07\x43PUInfo\x12%\n\x02id\x18\x01 \x01(\tB\x19\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12\x35\n\x06vendor\x18\x02 \x01(\tB%\xe2\xde\x1f\x06Vendor\xea\xde\x1f\x06vendor\xf2\xde\x1f\ryaml:\"vendor\"\x12\x31\n\x05model\x18\x03 \x01(\tB\"\xe2\xde\x1f\x05Model\xea\xde\x1f\x05model\xf2\xde\x1f\x0cyaml:\"model\"\x12\x35\n\x06vcores\x18\x04 \x01(\rB%\xe2\xde\x1f\x06Vcores\xea\xde\x1f\x06vcores\xf2\xde\x1f\ryaml:\"vcores\"\"\xc6\x01\n\x03\x43PU\x12\x63\n\x08quantity\x18\x01 \x01(\x0b\x32 .akash.inventory.v1.ResourcePairB/\xc8\xde\x1f\x00\xe2\xde\x1f\x08Quantity\xea\xde\x1f\x08quantity\xf2\xde\x1f\x0fyaml:\"quantity\"\x12Z\n\x04info\x18\x02 \x03(\x0b\x32\x1b.akash.inventory.v1.CPUInfoB/\xc8\xde\x1f\x00\xe2\xde\x1f\x04Info\xea\xde\x1f\x04info\xf2\xde\x1f\x0byaml:\"info\"\xaa\xdf\x1f\x08\x43PUInfoSB4Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.cpu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_CPUINFO'].fields_by_name['id']._options = None
  _globals['_CPUINFO'].fields_by_name['id']._serialized_options = b'\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_CPUINFO'].fields_by_name['vendor']._options = None
  _globals['_CPUINFO'].fields_by_name['vendor']._serialized_options = b'\342\336\037\006Vendor\352\336\037\006vendor\362\336\037\ryaml:\"vendor\"'
  _globals['_CPUINFO'].fields_by_name['model']._options = None
  _globals['_CPUINFO'].fields_by_name['model']._serialized_options = b'\342\336\037\005Model\352\336\037\005model\362\336\037\014yaml:\"model\"'
  _globals['_CPUINFO'].fields_by_name['vcores']._options = None
  _globals['_CPUINFO'].fields_by_name['vcores']._serialized_options = b'\342\336\037\006Vcores\352\336\037\006vcores\362\336\037\ryaml:\"vcores\"'
  _globals['_CPU'].fields_by_name['quantity']._options = None
  _globals['_CPU'].fields_by_name['quantity']._serialized_options = b'\310\336\037\000\342\336\037\010Quantity\352\336\037\010quantity\362\336\037\017yaml:\"quantity\"'
  _globals['_CPU'].fields_by_name['info']._options = None
  _globals['_CPU'].fields_by_name['info']._serialized_options = b'\310\336\037\000\342\336\037\004Info\352\336\037\004info\362\336\037\013yaml:\"info\"\252\337\037\010CPUInfoS'
  _globals['_CPUINFO']._serialized_start=114
  _globals['_CPUINFO']._serialized_end=323
  _globals['_CPU']._serialized_start=326
  _globals['_CPU']._serialized_end=524
# @@protoc_insertion_point(module_scope)
