# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/gpu.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.inventory.v1 import resourcepair_pb2 as akash_dot_inventory_dot_v1_dot_resourcepair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61kash/inventory/v1/gpu.proto\x12\x12\x61kash.inventory.v1\x1a\x14gogoproto/gogo.proto\x1a%akash/inventory/v1/resourcepair.proto\"\xfb\x02\n\x07GPUInfo\x12\x35\n\x06vendor\x18\x01 \x01(\tB%\xe2\xde\x1f\x06Vendor\xea\xde\x1f\x06vendor\xf2\xde\x1f\ryaml:\"vendor\"\x12@\n\tvendor_id\x18\x02 \x01(\tB-\xe2\xde\x1f\x08VendorID\xea\xde\x1f\tvendor_id\xf2\xde\x1f\x10yaml:\"vendor_id\"\x12-\n\x04name\x18\x03 \x01(\tB\x1f\xe2\xde\x1f\x04Name\xea\xde\x1f\x04name\xf2\xde\x1f\x0byaml:\"name\"\x12;\n\x07modelid\x18\x04 \x01(\tB*\xe2\xde\x1f\x07ModelID\xea\xde\x1f\x08model_id\xf2\xde\x1f\x0fyaml:\"model_id\"\x12\x41\n\tinterface\x18\x05 \x01(\tB.\xe2\xde\x1f\tInterface\xea\xde\x1f\tinterface\xf2\xde\x1f\x10yaml:\"interface\"\x12H\n\x0bmemory_size\x18\x06 \x01(\tB3\xe2\xde\x1f\nMemorySize\xea\xde\x1f\x0bmemory_size\xf2\xde\x1f\x12yaml:\"memory_size\"\"\xc6\x01\n\x03GPU\x12\x63\n\x08quantity\x18\x01 \x01(\x0b\x32 .akash.inventory.v1.ResourcePairB/\xc8\xde\x1f\x00\xe2\xde\x1f\x08Quantity\xea\xde\x1f\x08quantity\xf2\xde\x1f\x0fyaml:\"quantity\"\x12Z\n\x04info\x18\x02 \x03(\x0b\x32\x1b.akash.inventory.v1.GPUInfoB/\xc8\xde\x1f\x00\xe2\xde\x1f\x04Info\xea\xde\x1f\x04info\xf2\xde\x1f\x0byaml:\"info\"\xaa\xdf\x1f\x08GPUInfoSB4Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.gpu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_GPUINFO'].fields_by_name['vendor']._options = None
  _globals['_GPUINFO'].fields_by_name['vendor']._serialized_options = b'\342\336\037\006Vendor\352\336\037\006vendor\362\336\037\ryaml:\"vendor\"'
  _globals['_GPUINFO'].fields_by_name['vendor_id']._options = None
  _globals['_GPUINFO'].fields_by_name['vendor_id']._serialized_options = b'\342\336\037\010VendorID\352\336\037\tvendor_id\362\336\037\020yaml:\"vendor_id\"'
  _globals['_GPUINFO'].fields_by_name['name']._options = None
  _globals['_GPUINFO'].fields_by_name['name']._serialized_options = b'\342\336\037\004Name\352\336\037\004name\362\336\037\013yaml:\"name\"'
  _globals['_GPUINFO'].fields_by_name['modelid']._options = None
  _globals['_GPUINFO'].fields_by_name['modelid']._serialized_options = b'\342\336\037\007ModelID\352\336\037\010model_id\362\336\037\017yaml:\"model_id\"'
  _globals['_GPUINFO'].fields_by_name['interface']._options = None
  _globals['_GPUINFO'].fields_by_name['interface']._serialized_options = b'\342\336\037\tInterface\352\336\037\tinterface\362\336\037\020yaml:\"interface\"'
  _globals['_GPUINFO'].fields_by_name['memory_size']._options = None
  _globals['_GPUINFO'].fields_by_name['memory_size']._serialized_options = b'\342\336\037\nMemorySize\352\336\037\013memory_size\362\336\037\022yaml:\"memory_size\"'
  _globals['_GPU'].fields_by_name['quantity']._options = None
  _globals['_GPU'].fields_by_name['quantity']._serialized_options = b'\310\336\037\000\342\336\037\010Quantity\352\336\037\010quantity\362\336\037\017yaml:\"quantity\"'
  _globals['_GPU'].fields_by_name['info']._options = None
  _globals['_GPU'].fields_by_name['info']._serialized_options = b'\310\336\037\000\342\336\037\004Info\352\336\037\004info\362\336\037\013yaml:\"info\"\252\337\037\010GPUInfoS'
  _globals['_GPUINFO']._serialized_start=114
  _globals['_GPUINFO']._serialized_end=493
  _globals['_GPU']._serialized_start=496
  _globals['_GPU']._serialized_end=694
# @@protoc_insertion_point(module_scope)
