# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/memory.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.inventory.v1 import resourcepair_pb2 as akash_dot_inventory_dot_v1_dot_resourcepair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61kash/inventory/v1/memory.proto\x12\x12\x61kash.inventory.v1\x1a\x14gogoproto/gogo.proto\x1a%akash/inventory/v1/resourcepair.proto\"\xeb\x01\n\nMemoryInfo\x12\x35\n\x06vendor\x18\x01 \x01(\tB%\xe2\xde\x1f\x06Vendor\xea\xde\x1f\x06vendor\xf2\xde\x1f\ryaml:\"vendor\"\x12-\n\x04type\x18\x02 \x01(\tB\x1f\xe2\xde\x1f\x04Type\xea\xde\x1f\x04type\xf2\xde\x1f\x0byaml:\"type\"\x12\x44\n\ntotal_size\x18\x03 \x01(\tB0\xe2\xde\x1f\tTotalSize\xea\xde\x1f\ntotal_size\xf2\xde\x1f\x11yaml:\"total_size\"\x12\x31\n\x05speed\x18\x04 \x01(\tB\"\xe2\xde\x1f\x05Speed\xea\xde\x1f\x05speed\xf2\xde\x1f\x0cyaml:\"speed\"\"\xcf\x01\n\x06Memory\x12\x63\n\x08quantity\x18\x01 \x01(\x0b\x32 .akash.inventory.v1.ResourcePairB/\xc8\xde\x1f\x00\xe2\xde\x1f\x08Quantity\xea\xde\x1f\x08quantity\xf2\xde\x1f\x0fyaml:\"quantity\"\x12`\n\x04info\x18\x02 \x03(\x0b\x32\x1e.akash.inventory.v1.MemoryInfoB2\xc8\xde\x1f\x00\xe2\xde\x1f\x04Info\xea\xde\x1f\x04info\xf2\xde\x1f\x0byaml:\"info\"\xaa\xdf\x1f\x0bMemoryInfoSB4Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.memory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_MEMORYINFO'].fields_by_name['vendor']._options = None
  _globals['_MEMORYINFO'].fields_by_name['vendor']._serialized_options = b'\342\336\037\006Vendor\352\336\037\006vendor\362\336\037\ryaml:\"vendor\"'
  _globals['_MEMORYINFO'].fields_by_name['type']._options = None
  _globals['_MEMORYINFO'].fields_by_name['type']._serialized_options = b'\342\336\037\004Type\352\336\037\004type\362\336\037\013yaml:\"type\"'
  _globals['_MEMORYINFO'].fields_by_name['total_size']._options = None
  _globals['_MEMORYINFO'].fields_by_name['total_size']._serialized_options = b'\342\336\037\tTotalSize\352\336\037\ntotal_size\362\336\037\021yaml:\"total_size\"'
  _globals['_MEMORYINFO'].fields_by_name['speed']._options = None
  _globals['_MEMORYINFO'].fields_by_name['speed']._serialized_options = b'\342\336\037\005Speed\352\336\037\005speed\362\336\037\014yaml:\"speed\"'
  _globals['_MEMORY'].fields_by_name['quantity']._options = None
  _globals['_MEMORY'].fields_by_name['quantity']._serialized_options = b'\310\336\037\000\342\336\037\010Quantity\352\336\037\010quantity\362\336\037\017yaml:\"quantity\"'
  _globals['_MEMORY'].fields_by_name['info']._options = None
  _globals['_MEMORY'].fields_by_name['info']._serialized_options = b'\310\336\037\000\342\336\037\004Info\352\336\037\004info\362\336\037\013yaml:\"info\"\252\337\037\013MemoryInfoS'
  _globals['_MEMORYINFO']._serialized_start=117
  _globals['_MEMORYINFO']._serialized_end=352
  _globals['_MEMORY']._serialized_start=355
  _globals['_MEMORY']._serialized_end=562
# @@protoc_insertion_point(module_scope)
