# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/resources.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.inventory.v1 import cpu_pb2 as akash_dot_inventory_dot_v1_dot_cpu__pb2
from akash.proto.akash.inventory.v1 import gpu_pb2 as akash_dot_inventory_dot_v1_dot_gpu__pb2
from akash.proto.akash.inventory.v1 import memory_pb2 as akash_dot_inventory_dot_v1_dot_memory__pb2
from akash.proto.akash.inventory.v1 import resourcepair_pb2 as akash_dot_inventory_dot_v1_dot_resourcepair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"akash/inventory/v1/resources.proto\x12\x12\x61kash.inventory.v1\x1a\x14gogoproto/gogo.proto\x1a\x1c\x61kash/inventory/v1/cpu.proto\x1a\x1c\x61kash/inventory/v1/gpu.proto\x1a\x1f\x61kash/inventory/v1/memory.proto\x1a%akash/inventory/v1/resourcepair.proto\"\x8c\x05\n\rNodeResources\x12\x46\n\x03\x63pu\x18\x01 \x01(\x0b\x32\x17.akash.inventory.v1.CPUB \xc8\xde\x1f\x00\xe2\xde\x1f\x03\x43PU\xea\xde\x1f\x03\x63pu\xf2\xde\x1f\nyaml:\"cpu\"\x12U\n\x06memory\x18\x02 \x01(\x0b\x32\x1a.akash.inventory.v1.MemoryB)\xc8\xde\x1f\x00\xe2\xde\x1f\x06Memory\xea\xde\x1f\x06memory\xf2\xde\x1f\ryaml:\"memory\"\x12N\n\x03gpu\x18\x03 \x01(\x0b\x32\x17.akash.inventory.v1.GPUB(\xc8\xde\x1f\x00\xe2\xde\x1f\x03GPU\xea\xde\x1f\x03gpu\xf2\xde\x1f\nyaml:\"gpu\"\xaa\xdf\x1f\x04GPUs\x12\x86\x01\n\x11\x65phemeral_storage\x18\x04 \x01(\x0b\x32 .akash.inventory.v1.ResourcePairBI\xc8\xde\x1f\x00\xe2\xde\x1f\x10\x45phemeralStorage\xea\xde\x1f\x11\x65phemeral_storage\xf2\xde\x1f\x18yaml:\"ephemeral_storage\"\x12\x82\x01\n\x10volumes_attached\x18\x05 \x01(\x0b\x32 .akash.inventory.v1.ResourcePairBF\xc8\xde\x1f\x00\xe2\xde\x1f\x0fVolumesAttached\xea\xde\x1f\x10volumes_attached\xf2\xde\x1f\x17yaml:\"volumes_attached\"\x12~\n\x0fvolumes_mounted\x18\x06 \x01(\x0b\x32 .akash.inventory.v1.ResourcePairBC\xc8\xde\x1f\x00\xe2\xde\x1f\x0eVolumesMounted\xea\xde\x1f\x0fvolumes_mounted\xf2\xde\x1f\x16yaml:\"volumes_mounted\"B4Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.resources_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_NODERESOURCES'].fields_by_name['cpu']._options = None
  _globals['_NODERESOURCES'].fields_by_name['cpu']._serialized_options = b'\310\336\037\000\342\336\037\003CPU\352\336\037\003cpu\362\336\037\nyaml:\"cpu\"'
  _globals['_NODERESOURCES'].fields_by_name['memory']._options = None
  _globals['_NODERESOURCES'].fields_by_name['memory']._serialized_options = b'\310\336\037\000\342\336\037\006Memory\352\336\037\006memory\362\336\037\ryaml:\"memory\"'
  _globals['_NODERESOURCES'].fields_by_name['gpu']._options = None
  _globals['_NODERESOURCES'].fields_by_name['gpu']._serialized_options = b'\310\336\037\000\342\336\037\003GPU\352\336\037\003gpu\362\336\037\nyaml:\"gpu\"\252\337\037\004GPUs'
  _globals['_NODERESOURCES'].fields_by_name['ephemeral_storage']._options = None
  _globals['_NODERESOURCES'].fields_by_name['ephemeral_storage']._serialized_options = b'\310\336\037\000\342\336\037\020EphemeralStorage\352\336\037\021ephemeral_storage\362\336\037\030yaml:\"ephemeral_storage\"'
  _globals['_NODERESOURCES'].fields_by_name['volumes_attached']._options = None
  _globals['_NODERESOURCES'].fields_by_name['volumes_attached']._serialized_options = b'\310\336\037\000\342\336\037\017VolumesAttached\352\336\037\020volumes_attached\362\336\037\027yaml:\"volumes_attached\"'
  _globals['_NODERESOURCES'].fields_by_name['volumes_mounted']._options = None
  _globals['_NODERESOURCES'].fields_by_name['volumes_mounted']._serialized_options = b'\310\336\037\000\342\336\037\016VolumesMounted\352\336\037\017volumes_mounted\362\336\037\026yaml:\"volumes_mounted\"'
  _globals['_NODERESOURCES']._serialized_start=213
  _globals['_NODERESOURCES']._serialized_end=865
# @@protoc_insertion_point(module_scope)
