# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/resourcepair.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.v1beta3 import attribute_pb2 as akash_dot_base_dot_v1beta3_dot_attribute__pb2
from akash.proto.k8s.io.apimachinery.pkg.api.resource import generated_pb2 as k8s_dot_io_dot_apimachinery_dot_pkg_dot_api_dot_resource_dot_generated__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%akash/inventory/v1/resourcepair.proto\x12\x12\x61kash.inventory.v1\x1a\x14gogoproto/gogo.proto\x1a\"akash/base/v1beta3/attribute.proto\x1a\x34k8s.io/apimachinery/pkg/api/resource/generated.proto\"\xb6\x04\n\x0cResourcePair\x12}\n\x0b\x61llocatable\x18\x01 \x01(\x0b\x32..k8s.io.apimachinery.pkg.api.resource.QuantityB8\xc8\xde\x1f\x01\xe2\xde\x1f\x0b\x41llocatable\xea\xde\x1f\x0b\x61llocatable\xf2\xde\x1f\x12yaml:\"allocatable\"\x12u\n\tallocated\x18\x02 \x01(\x0b\x32..k8s.io.apimachinery.pkg.api.resource.QuantityB2\xc8\xde\x1f\x01\xe2\xde\x1f\tAllocated\xea\xde\x1f\tallocated\xf2\xde\x1f\x10yaml:\"allocated\"\x12\xb6\x01\n\nattributes\x18\x03 \x03(\x0b\x32\x1d.akash.base.v1beta3.AttributeB\x82\x01\xc8\xde\x1f\x00\xea\xde\x1f\x14\x61ttributes,omitempty\xf2\xde\x1f\x1byaml:\"attributes,omitempty\"\xaa\xdf\x1f\x43github.com/akash-network/akash-api/go/node/types/v1beta3.Attributes\x12q\n\x08\x63\x61pacity\x18\x04 \x01(\x0b\x32..k8s.io.apimachinery.pkg.api.resource.QuantityB/\xc8\xde\x1f\x01\xe2\xde\x1f\x08\x43\x61pacity\xea\xde\x1f\x08\x63\x61pacity\xf2\xde\x1f\x0fyaml:\"capacity\":\x04\xe8\xa0\x1f\x00\x42\x34Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.resourcepair_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_RESOURCEPAIR'].fields_by_name['allocatable']._options = None
  _globals['_RESOURCEPAIR'].fields_by_name['allocatable']._serialized_options = b'\310\336\037\001\342\336\037\013Allocatable\352\336\037\013allocatable\362\336\037\022yaml:\"allocatable\"'
  _globals['_RESOURCEPAIR'].fields_by_name['allocated']._options = None
  _globals['_RESOURCEPAIR'].fields_by_name['allocated']._serialized_options = b'\310\336\037\001\342\336\037\tAllocated\352\336\037\tallocated\362\336\037\020yaml:\"allocated\"'
  _globals['_RESOURCEPAIR'].fields_by_name['attributes']._options = None
  _globals['_RESOURCEPAIR'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\024attributes,omitempty\362\336\037\033yaml:\"attributes,omitempty\"\252\337\037Cgithub.com/akash-network/akash-api/go/node/types/v1beta3.Attributes'
  _globals['_RESOURCEPAIR'].fields_by_name['capacity']._options = None
  _globals['_RESOURCEPAIR'].fields_by_name['capacity']._serialized_options = b'\310\336\037\001\342\336\037\010Capacity\352\336\037\010capacity\362\336\037\017yaml:\"capacity\"'
  _globals['_RESOURCEPAIR']._options = None
  _globals['_RESOURCEPAIR']._serialized_options = b'\350\240\037\000'
  _globals['_RESOURCEPAIR']._serialized_start=174
  _globals['_RESOURCEPAIR']._serialized_end=740
# @@protoc_insertion_point(module_scope)
