# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/service.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from akash.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from akash.proto.akash.inventory.v1 import node_pb2 as akash_dot_inventory_dot_v1_dot_node__pb2
from akash.proto.akash.inventory.v1 import cluster_pb2 as akash_dot_inventory_dot_v1_dot_cluster__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n akash/inventory/v1/service.proto\x12\x12\x61kash.inventory.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1d\x61kash/inventory/v1/node.proto\x1a akash/inventory/v1/cluster.proto2\x9f\x01\n\x07NodeRPC\x12R\n\tQueryNode\x12\x16.google.protobuf.Empty\x1a\x18.akash.inventory.v1.Node\"\x13\x82\xd3\xe4\x93\x02\r\x12\x08/v1/nodeb\x01*\x12@\n\nStreamNode\x12\x16.google.protobuf.Empty\x1a\x18.akash.inventory.v1.Node0\x01\x32\xb3\x01\n\nClusterRPC\x12]\n\x0cQueryCluster\x12\x16.google.protobuf.Empty\x1a\x1b.akash.inventory.v1.Cluster\"\x18\x82\xd3\xe4\x93\x02\x12\x12\r/v1/inventoryb\x01*\x12\x46\n\rStreamCluster\x12\x16.google.protobuf.Empty\x1a\x1b.akash.inventory.v1.Cluster0\x01\x42\x34Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_NODERPC'].methods_by_name['QueryNode']._options = None
  _globals['_NODERPC'].methods_by_name['QueryNode']._serialized_options = b'\202\323\344\223\002\r\022\010/v1/nodeb\001*'
  _globals['_CLUSTERRPC'].methods_by_name['QueryCluster']._options = None
  _globals['_CLUSTERRPC'].methods_by_name['QueryCluster']._serialized_options = b'\202\323\344\223\002\022\022\r/v1/inventoryb\001*'
  _globals['_NODERPC']._serialized_start=181
  _globals['_NODERPC']._serialized_end=340
  _globals['_CLUSTERRPC']._serialized_start=343
  _globals['_CLUSTERRPC']._serialized_end=522
# @@protoc_insertion_point(module_scope)
