# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/inventory/v1/storage.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.inventory.v1 import resourcepair_pb2 as akash_dot_inventory_dot_v1_dot_resourcepair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n akash/inventory/v1/storage.proto\x12\x12\x61kash.inventory.v1\x1a\x14gogoproto/gogo.proto\x1a%akash/inventory/v1/resourcepair.proto\"o\n\x0bStorageInfo\x12\x31\n\x05\x63lass\x18\x01 \x01(\tB\"\xe2\xde\x1f\x05\x43lass\xea\xde\x1f\x05\x63lass\xf2\xde\x1f\x0cyaml:\"class\"\x12-\n\x04iops\x18\x02 \x01(\tB\x1f\xe2\xde\x1f\x04IOPS\xea\xde\x1f\x04iops\xf2\xde\x1f\x0byaml:\"iops\"\"\xc2\x01\n\x07Storage\x12\x63\n\x08quantity\x18\x01 \x01(\x0b\x32 .akash.inventory.v1.ResourcePairB/\xc8\xde\x1f\x00\xe2\xde\x1f\x08Quantity\xea\xde\x1f\x08quantity\xf2\xde\x1f\x0fyaml:\"quantity\"\x12R\n\x04info\x18\x02 \x01(\x0b\x32\x1f.akash.inventory.v1.StorageInfoB#\xc8\xde\x1f\x00\xe2\xde\x1f\x04Info\xea\xde\x1f\x04info\xf2\xde\x1f\x0byaml:\"info\"B4Z2github.com/akash-network/akash-api/go/inventory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.inventory.v1.storage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/akash-network/akash-api/go/inventory/v1'
  _globals['_STORAGEINFO'].fields_by_name['class']._options = None
  _globals['_STORAGEINFO'].fields_by_name['class']._serialized_options = b'\342\336\037\005Class\352\336\037\005class\362\336\037\014yaml:\"class\"'
  _globals['_STORAGEINFO'].fields_by_name['iops']._options = None
  _globals['_STORAGEINFO'].fields_by_name['iops']._serialized_options = b'\342\336\037\004IOPS\352\336\037\004iops\362\336\037\013yaml:\"iops\"'
  _globals['_STORAGE'].fields_by_name['quantity']._options = None
  _globals['_STORAGE'].fields_by_name['quantity']._serialized_options = b'\310\336\037\000\342\336\037\010Quantity\352\336\037\010quantity\362\336\037\017yaml:\"quantity\"'
  _globals['_STORAGE'].fields_by_name['info']._options = None
  _globals['_STORAGE'].fields_by_name['info']._serialized_options = b'\310\336\037\000\342\336\037\004Info\352\336\037\004info\362\336\037\013yaml:\"info\"'
  _globals['_STORAGEINFO']._serialized_start=117
  _globals['_STORAGEINFO']._serialized_end=228
  _globals['_STORAGE']._serialized_start=231
  _globals['_STORAGE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
