# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta2/service.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.akash.deployment.v1beta2 import deploymentmsg_pb2 as akash_dot_deployment_dot_v1beta2_dot_deploymentmsg__pb2
from akash.proto.akash.deployment.v1beta2 import groupmsg_pb2 as akash_dot_deployment_dot_v1beta2_dot_groupmsg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&akash/deployment/v1beta2/service.proto\x12\x18\x61kash.deployment.v1beta2\x1a,akash/deployment/v1beta2/deploymentmsg.proto\x1a\'akash/deployment/v1beta2/groupmsg.proto2\xa5\x06\n\x03Msg\x12x\n\x10\x43reateDeployment\x12-.akash.deployment.v1beta2.MsgCreateDeployment\x1a\x35.akash.deployment.v1beta2.MsgCreateDeploymentResponse\x12{\n\x11\x44\x65positDeployment\x12..akash.deployment.v1beta2.MsgDepositDeployment\x1a\x36.akash.deployment.v1beta2.MsgDepositDeploymentResponse\x12x\n\x10UpdateDeployment\x12-.akash.deployment.v1beta2.MsgUpdateDeployment\x1a\x35.akash.deployment.v1beta2.MsgUpdateDeploymentResponse\x12u\n\x0f\x43loseDeployment\x12,.akash.deployment.v1beta2.MsgCloseDeployment\x1a\x34.akash.deployment.v1beta2.MsgCloseDeploymentResponse\x12\x66\n\nCloseGroup\x12\'.akash.deployment.v1beta2.MsgCloseGroup\x1a/.akash.deployment.v1beta2.MsgCloseGroupResponse\x12\x66\n\nPauseGroup\x12\'.akash.deployment.v1beta2.MsgPauseGroup\x1a/.akash.deployment.v1beta2.MsgPauseGroupResponse\x12\x66\n\nStartGroup\x12\'.akash.deployment.v1beta2.MsgStartGroup\x1a/.akash.deployment.v1beta2.MsgStartGroupResponseB?Z=github.com/akash-network/akash-api/go/node/deployment/v1beta2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta2.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/akash-network/akash-api/go/node/deployment/v1beta2'
  _globals['_MSG']._serialized_start=156
  _globals['_MSG']._serialized_end=961
# @@protoc_insertion_point(module_scope)
