# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta3/deployment.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)akash/deployment/v1beta3/deployment.proto\x12\x18\x61kash.deployment.v1beta3\x1a\x14gogoproto/gogo.proto\"q\n\x0c\x44\x65ploymentID\x12(\n\x05owner\x18\x01 \x01(\tB\x19\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\x12-\n\x04\x64seq\x18\x02 \x01(\x04\x42\x1f\xe2\xde\x1f\x04\x44Seq\xea\xde\x1f\x04\x64seq\xf2\xde\x1f\x0byaml:\"dseq\":\x08\x98\xa0\x1f\x00\xe8\xa0\x1f\x00\"\x90\x03\n\nDeployment\x12\x66\n\rdeployment_id\x18\x01 \x01(\x0b\x32&.akash.deployment.v1beta3.DeploymentIDB\'\xc8\xde\x1f\x00\xe2\xde\x1f\x0c\x44\x65ploymentID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12T\n\x05state\x18\x02 \x01(\x0e\x32*.akash.deployment.v1beta3.Deployment.StateB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"\x12.\n\x07version\x18\x03 \x01(\x0c\x42\x1d\xea\xde\x1f\x07version\xf2\xde\x1f\x0eyaml:\"version\"\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"z\n\x05State\x12\'\n\x07invalid\x10\x00\x1a\x1a\x8a\x9d \x16\x44\x65ploymentStateInvalid\x12 \n\x06\x61\x63tive\x10\x01\x1a\x14\x8a\x9d \x10\x44\x65ploymentActive\x12 \n\x06\x63losed\x10\x02\x1a\x14\x8a\x9d \x10\x44\x65ploymentClosed\x1a\x04\x88\xa3\x1e\x00:\x04\xe8\xa0\x1f\x00\"\x9c\x01\n\x11\x44\x65ploymentFilters\x12(\n\x05owner\x18\x01 \x01(\tB\x19\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\x12-\n\x04\x64seq\x18\x02 \x01(\x04\x42\x1f\xe2\xde\x1f\x04\x44Seq\xea\xde\x1f\x04\x64seq\xf2\xde\x1f\x0byaml:\"dseq\"\x12(\n\x05state\x18\x03 \x01(\tB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\":\x04\xe8\xa0\x1f\x00\x42?Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta3.deployment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3'
  _globals['_DEPLOYMENTID'].fields_by_name['owner']._options = None
  _globals['_DEPLOYMENTID'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"'
  _globals['_DEPLOYMENTID'].fields_by_name['dseq']._options = None
  _globals['_DEPLOYMENTID'].fields_by_name['dseq']._serialized_options = b'\342\336\037\004DSeq\352\336\037\004dseq\362\336\037\013yaml:\"dseq\"'
  _globals['_DEPLOYMENTID']._options = None
  _globals['_DEPLOYMENTID']._serialized_options = b'\230\240\037\000\350\240\037\000'
  _globals['_DEPLOYMENT_STATE']._options = None
  _globals['_DEPLOYMENT_STATE']._serialized_options = b'\210\243\036\000'
  _globals['_DEPLOYMENT_STATE'].values_by_name["invalid"]._options = None
  _globals['_DEPLOYMENT_STATE'].values_by_name["invalid"]._serialized_options = b'\212\235 \026DeploymentStateInvalid'
  _globals['_DEPLOYMENT_STATE'].values_by_name["active"]._options = None
  _globals['_DEPLOYMENT_STATE'].values_by_name["active"]._serialized_options = b'\212\235 \020DeploymentActive'
  _globals['_DEPLOYMENT_STATE'].values_by_name["closed"]._options = None
  _globals['_DEPLOYMENT_STATE'].values_by_name["closed"]._serialized_options = b'\212\235 \020DeploymentClosed'
  _globals['_DEPLOYMENT'].fields_by_name['deployment_id']._options = None
  _globals['_DEPLOYMENT'].fields_by_name['deployment_id']._serialized_options = b'\310\336\037\000\342\336\037\014DeploymentID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_DEPLOYMENT'].fields_by_name['state']._options = None
  _globals['_DEPLOYMENT'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_DEPLOYMENT'].fields_by_name['version']._options = None
  _globals['_DEPLOYMENT'].fields_by_name['version']._serialized_options = b'\352\336\037\007version\362\336\037\016yaml:\"version\"'
  _globals['_DEPLOYMENT']._options = None
  _globals['_DEPLOYMENT']._serialized_options = b'\350\240\037\000'
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['owner']._options = None
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"'
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['dseq']._options = None
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['dseq']._serialized_options = b'\342\336\037\004DSeq\352\336\037\004dseq\362\336\037\013yaml:\"dseq\"'
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['state']._options = None
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_DEPLOYMENTFILTERS']._options = None
  _globals['_DEPLOYMENTFILTERS']._serialized_options = b'\350\240\037\000'
  _globals['_DEPLOYMENTID']._serialized_start=93
  _globals['_DEPLOYMENTID']._serialized_end=206
  _globals['_DEPLOYMENT']._serialized_start=209
  _globals['_DEPLOYMENT']._serialized_end=609
  _globals['_DEPLOYMENT_STATE']._serialized_start=481
  _globals['_DEPLOYMENT_STATE']._serialized_end=603
  _globals['_DEPLOYMENTFILTERS']._serialized_start=612
  _globals['_DEPLOYMENTFILTERS']._serialized_end=768
# @@protoc_insertion_point(module_scope)
