# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta3/groupspec.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.v1beta3 import attribute_pb2 as akash_dot_base_dot_v1beta3_dot_attribute__pb2
from akash.proto.akash.deployment.v1beta3 import resourceunit_pb2 as akash_dot_deployment_dot_v1beta3_dot_resourceunit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(akash/deployment/v1beta3/groupspec.proto\x12\x18\x61kash.deployment.v1beta3\x1a\x14gogoproto/gogo.proto\x1a\"akash/base/v1beta3/attribute.proto\x1a+akash/deployment/v1beta3/resourceunit.proto\"\x9d\x02\n\tGroupSpec\x12%\n\x04name\x18\x01 \x01(\tB\x17\xea\xde\x1f\x04name\xf2\xde\x1f\x0byaml:\"name\"\x12l\n\x0crequirements\x18\x02 \x01(\x0b\x32).akash.base.v1beta3.PlacementRequirementsB+\xc8\xde\x1f\x00\xea\xde\x1f\x0crequirements\xf2\xde\x1f\x13yaml:\"requirements\"\x12q\n\tresources\x18\x03 \x03(\x0b\x32&.akash.deployment.v1beta3.ResourceUnitB6\xc8\xde\x1f\x00\xea\xde\x1f\tresources\xf2\xde\x1f\x10yaml:\"resources\"\xaa\xdf\x1f\rResourceUnits:\x08\x88\xa0\x1f\x00\xe8\xa0\x1f\x00\x42?Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta3.groupspec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3'
  _globals['_GROUPSPEC'].fields_by_name['name']._options = None
  _globals['_GROUPSPEC'].fields_by_name['name']._serialized_options = b'\352\336\037\004name\362\336\037\013yaml:\"name\"'
  _globals['_GROUPSPEC'].fields_by_name['requirements']._options = None
  _globals['_GROUPSPEC'].fields_by_name['requirements']._serialized_options = b'\310\336\037\000\352\336\037\014requirements\362\336\037\023yaml:\"requirements\"'
  _globals['_GROUPSPEC'].fields_by_name['resources']._options = None
  _globals['_GROUPSPEC'].fields_by_name['resources']._serialized_options = b'\310\336\037\000\352\336\037\tresources\362\336\037\020yaml:\"resources\"\252\337\037\rResourceUnits'
  _globals['_GROUPSPEC']._options = None
  _globals['_GROUPSPEC']._serialized_options = b'\210\240\037\000\350\240\037\000'
  _globals['_GROUPSPEC']._serialized_start=174
  _globals['_GROUPSPEC']._serialized_end=459
# @@protoc_insertion_point(module_scope)
