# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta3/params.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%akash/deployment/v1beta3/params.proto\x12\x18\x61kash.deployment.v1beta3\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\xa2\x01\n\x06Params\x12\x97\x01\n\x0cmin_deposits\x18\x01 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinBf\xc8\xde\x1f\x00\xe2\xde\x1f\x0bMinDeposits\xea\xde\x1f\x0cmin_deposits\xf2\xde\x1f\x13yaml:\"min_deposits\"\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.CoinsB?Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta3.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3'
  _globals['_PARAMS'].fields_by_name['min_deposits']._options = None
  _globals['_PARAMS'].fields_by_name['min_deposits']._serialized_options = b'\310\336\037\000\342\336\037\013MinDeposits\352\336\037\014min_deposits\362\336\037\023yaml:\"min_deposits\"\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins'
  _globals['_PARAMS']._serialized_start=122
  _globals['_PARAMS']._serialized_end=284
# @@protoc_insertion_point(module_scope)
