# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta3/resourceunit.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.v1beta3 import resources_pb2 as akash_dot_base_dot_v1beta3_dot_resources__pb2
from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+akash/deployment/v1beta3/resourceunit.proto\x12\x18\x61kash.deployment.v1beta3\x1a\x14gogoproto/gogo.proto\x1a\"akash/base/v1beta3/resources.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\xe4\x01\n\x0cResourceUnit\x12X\n\x08resource\x18\x01 \x01(\x0b\x32\x1d.akash.base.v1beta3.ResourcesB\'\xc8\xde\x1f\x00\xd0\xde\x1f\x01\xea\xde\x1f\x08resource\xf2\xde\x1f\x0fyaml:\"resource\"\x12(\n\x05\x63ount\x18\x02 \x01(\rB\x19\xea\xde\x1f\x05\x63ount\xf2\xde\x1f\x0cyaml:\"count\"\x12J\n\x05price\x18\x03 \x01(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinB\x1d\xc8\xde\x1f\x00\xea\xde\x1f\x05price\xf2\xde\x1f\x0cyaml:\"price\":\x04\xe8\xa0\x1f\x01\x42?Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta3.resourceunit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/akash-network/akash-api/go/node/deployment/v1beta3'
  _globals['_RESOURCEUNIT'].fields_by_name['resource']._options = None
  _globals['_RESOURCEUNIT'].fields_by_name['resource']._serialized_options = b'\310\336\037\000\320\336\037\001\352\336\037\010resource\362\336\037\017yaml:\"resource\"'
  _globals['_RESOURCEUNIT'].fields_by_name['count']._options = None
  _globals['_RESOURCEUNIT'].fields_by_name['count']._serialized_options = b'\352\336\037\005count\362\336\037\014yaml:\"count\"'
  _globals['_RESOURCEUNIT'].fields_by_name['price']._options = None
  _globals['_RESOURCEUNIT'].fields_by_name['price']._serialized_options = b'\310\336\037\000\352\336\037\005price\362\336\037\014yaml:\"price\"'
  _globals['_RESOURCEUNIT']._options = None
  _globals['_RESOURCEUNIT']._serialized_options = b'\350\240\037\001'
  _globals['_RESOURCEUNIT']._serialized_start=164
  _globals['_RESOURCEUNIT']._serialized_end=392
# @@protoc_insertion_point(module_scope)
