# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/gov/v1beta3/genesis.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.gov.v1beta3 import params_pb2 as akash_dot_gov_dot_v1beta3_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61kash/gov/v1beta3/genesis.proto\x12\x11\x61kash.gov.v1beta3\x1a\x14gogoproto/gogo.proto\x1a\x1e\x61kash/gov/v1beta3/params.proto\"y\n\x0cGenesisState\x12i\n\x0e\x64\x65posit_params\x18\x01 \x01(\x0b\x32 .akash.gov.v1beta3.DepositParamsB/\xc8\xde\x1f\x00\xea\xde\x1f\x0e\x64\x65posit_params\xf2\xde\x1f\x15yaml:\"deposit_params\"B8Z6github.com/akash-network/akash-api/go/node/gov/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.gov.v1beta3.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/akash-network/akash-api/go/node/gov/v1beta3'
  _globals['_GENESISSTATE'].fields_by_name['deposit_params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['deposit_params']._serialized_options = b'\310\336\037\000\352\336\037\016deposit_params\362\336\037\025yaml:\"deposit_params\"'
  _globals['_GENESISSTATE']._serialized_start=108
  _globals['_GENESISSTATE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
