# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta4/params.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!akash/market/v1beta4/params.proto\x12\x14\x61kash.market.v1beta4\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\xd5\x01\n\x06Params\x12v\n\x0f\x62id_min_deposit\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinBB\xc8\xde\x1f\x00\xe2\xde\x1f\rBidMinDeposit\xea\xde\x1f\x0f\x62id_min_deposit\xf2\xde\x1f\x16yaml:\"bid_min_deposit\"\x12S\n\x0eorder_max_bids\x18\x02 \x01(\rB;\xe2\xde\x1f\x0cOrderMaxBids\xea\xde\x1f\x0eorder_max_bids\xf2\xde\x1f\x15yaml:\"order_max_bids\"B;Z9github.com/akash-network/akash-api/go/node/market/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta4.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/akash-network/akash-api/go/node/market/v1beta4'
  _globals['_PARAMS'].fields_by_name['bid_min_deposit']._options = None
  _globals['_PARAMS'].fields_by_name['bid_min_deposit']._serialized_options = b'\310\336\037\000\342\336\037\rBidMinDeposit\352\336\037\017bid_min_deposit\362\336\037\026yaml:\"bid_min_deposit\"'
  _globals['_PARAMS'].fields_by_name['order_max_bids']._options = None
  _globals['_PARAMS'].fields_by_name['order_max_bids']._serialized_options = b'\342\336\037\014OrderMaxBids\352\336\037\016order_max_bids\362\336\037\025yaml:\"order_max_bids\"'
  _globals['_PARAMS']._serialized_start=114
  _globals['_PARAMS']._serialized_end=327
# @@protoc_insertion_point(module_scope)
