# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/manifest/v2beta2/group.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.manifest.v2beta2 import service_pb2 as akash_dot_manifest_dot_v2beta2_dot_service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"akash/manifest/v2beta2/group.proto\x12\x16\x61kash.manifest.v2beta2\x1a\x14gogoproto/gogo.proto\x1a$akash/manifest/v2beta2/service.proto\"\x98\x01\n\x05Group\x12%\n\x04name\x18\x01 \x01(\tB\x17\xea\xde\x1f\x04name\xf2\xde\x1f\x0byaml:\"name\"\x12\x62\n\x08services\x18\x02 \x03(\x0b\x32\x1f.akash.manifest.v2beta2.ServiceB/\xc8\xde\x1f\x00\xea\xde\x1f\x08services\xf2\xde\x1f\x0fyaml:\"services\"\xaa\xdf\x1f\x08Services:\x04\x88\xa0\x1f\x00\x42@Z6github.com/akash-network/akash-api/go/manifest/v2beta2\xd8\xe1\x1e\x00\x80\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.manifest.v2beta2.group_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/akash-network/akash-api/go/manifest/v2beta2\330\341\036\000\200\342\036\001'
  _globals['_GROUP'].fields_by_name['name']._options = None
  _globals['_GROUP'].fields_by_name['name']._serialized_options = b'\352\336\037\004name\362\336\037\013yaml:\"name\"'
  _globals['_GROUP'].fields_by_name['services']._options = None
  _globals['_GROUP'].fields_by_name['services']._serialized_options = b'\310\336\037\000\352\336\037\010services\362\336\037\017yaml:\"services\"\252\337\037\010Services'
  _globals['_GROUP']._options = None
  _globals['_GROUP']._serialized_options = b'\210\240\037\000'
  _globals['_GROUP']._serialized_start=123
  _globals['_GROUP']._serialized_end=275
# @@protoc_insertion_point(module_scope)
