# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/take/v1beta3/params.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61kash/take/v1beta3/params.proto\x12\x12\x61kash.take.v1beta3\x1a\x14gogoproto/gogo.proto\"q\n\rDenomTakeRate\x12\x31\n\x05\x64\x65nom\x18\x01 \x01(\tB\"\xe2\xde\x1f\x05\x44\x65nom\xea\xde\x1f\x05\x64\x65nom\xf2\xde\x1f\x0cyaml:\"denom\"\x12-\n\x04rate\x18\x02 \x01(\rB\x1f\xe2\xde\x1f\x04Rate\xea\xde\x1f\x04rate\xf2\xde\x1f\x0byaml:\"rate\"\"\x80\x02\n\x06Params\x12\x94\x01\n\x10\x64\x65nom_take_rates\x18\x01 \x03(\x0b\x32!.akash.take.v1beta3.DenomTakeRateBW\xc8\xde\x1f\x00\xe2\xde\x1f\x0e\x44\x65nomTakeRates\xea\xde\x1f\x10\x64\x65nom_take_rates\xf2\xde\x1f\x17yaml:\"denom_take_rates\"\xaa\xdf\x1f\x0e\x44\x65nomTakeRates\x12_\n\x11\x64\x65\x66\x61ult_take_rate\x18\x02 \x01(\rBD\xe2\xde\x1f\x0f\x44\x65\x66\x61ultTakeRate\xea\xde\x1f\x11\x64\x65\x66\x61ult_take_rate\xf2\xde\x1f\x18yaml:\"default_take_rate\"B9Z7github.com/akash-network/akash-api/go/node/take/v1beta3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.take.v1beta3.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/akash-network/akash-api/go/node/take/v1beta3'
  _globals['_DENOMTAKERATE'].fields_by_name['denom']._options = None
  _globals['_DENOMTAKERATE'].fields_by_name['denom']._serialized_options = b'\342\336\037\005Denom\352\336\037\005denom\362\336\037\014yaml:\"denom\"'
  _globals['_DENOMTAKERATE'].fields_by_name['rate']._options = None
  _globals['_DENOMTAKERATE'].fields_by_name['rate']._serialized_options = b'\342\336\037\004Rate\352\336\037\004rate\362\336\037\013yaml:\"rate\"'
  _globals['_PARAMS'].fields_by_name['denom_take_rates']._options = None
  _globals['_PARAMS'].fields_by_name['denom_take_rates']._serialized_options = b'\310\336\037\000\342\336\037\016DenomTakeRates\352\336\037\020denom_take_rates\362\336\037\027yaml:\"denom_take_rates\"\252\337\037\016DenomTakeRates'
  _globals['_PARAMS'].fields_by_name['default_take_rate']._options = None
  _globals['_PARAMS'].fields_by_name['default_take_rate']._serialized_options = b'\342\336\037\017DefaultTakeRate\352\336\037\021default_take_rate\362\336\037\030yaml:\"default_take_rate\"'
  _globals['_DENOMTAKERATE']._serialized_start=77
  _globals['_DENOMTAKERATE']._serialized_end=190
  _globals['_PARAMS']._serialized_start=193
  _globals['_PARAMS']._serialized_end=449
# @@protoc_insertion_point(module_scope)
