# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/discovery/v1/client_info.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$akash/discovery/v1/client_info.proto\x12\x12\x61kash.discovery.v1\x1a\x14gogoproto/gogo.proto\"V\n\nClientInfo\x12H\n\x0b\x61pi_version\x18\x01 \x01(\tB3\xe2\xde\x1f\nApiVersion\xea\xde\x1f\x0b\x61pi_version\xf2\xde\x1f\x12yaml:\"api_version\"B3Z1github.com/akash-network/akash-api/go/node/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.discovery.v1.client_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/akash-network/akash-api/go/node/client'
  _globals['_CLIENTINFO'].fields_by_name['api_version']._options = None
  _globals['_CLIENTINFO'].fields_by_name['api_version']._serialized_options = b'\342\336\037\nApiVersion\352\336\037\013api_version\362\336\037\022yaml:\"api_version\"'
  _globals['_CLIENTINFO']._serialized_start=82
  _globals['_CLIENTINFO']._serialized_end=168
# @@protoc_insertion_point(module_scope)
